apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: prom-tail
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: promtail
    # helm:
    #   values: |-
    #     config:
    #        clients:
    #         - url: http://loki/loki/api/v1/push
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.11.3
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true